services:
  db:
    image: postgres:16
    container_name: iss-postgres
    environment:
      POSTGRES_DB: iss
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: vesper
    ports:
      - "5433:5432"
    volumes:
      - iss_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgadmin -d iss"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  iss_pg_data:
